name: git_touch
description: A new Flutter project.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.11.1+20

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  artemis: ^3.2.1
  cupertino_icons: ^1.0.0
  file_icon: ^0.3.0
  filesize: ^1.0.4
  fimber: ^0.4.4
  fluro: ^1.7.8
  flutter_highlight: ^0.6.0
  flutter_markdown: ^0.4.4
  flutter_svg: ^0.19.0
  flutter_vector_icons: ^0.2.1
  github: ^7.0.3
  github_trending: ^1.0.0
  http: ^0.12.0
  # in_app_review: ^1.0.4
  intl: ^0.16.0
  json_annotation: ^3.1.1
  launch_review: ^2.0.0
  nanoid: ^0.1.0
  package_info: ^0.4.0
  primer: ^0.0.2
  provider: ^4.3.2
  share: ^0.6.0
  shared_preferences: ^0.5.6
  timeago: ^2.0.18
  tuple: ^1.0.2
  uni_links: ^0.4.0
  universal_io: ^1.0.1
  uri: ^0.11.3
  url_launcher: ^5.4.1
  webview_flutter: ^1.0.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3
  json_serializable: ^3.5.1

# dependencies_overrides:
#   flutter_highlight:
#     path: ../highlight/flutter_highlight
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Fira Code
      fonts:
        - asset: fonts/FiraCode-Regular.ttf
        - asset: fonts/FiraCode-Bold.ttf
          weight: 700
    - family: Inconsolata
      fonts:
        - asset: fonts/Inconsolata-Regular.ttf
        - asset: fonts/Inconsolata-Bold.ttf
          weight: 700
    - family: PT Mono
      fonts:
        - asset: fonts/PTMono-Regular.ttf
    - family: Source Code Pro
      fonts:
        - asset: fonts/SourceCodePro-Regular.ttf
        - asset: fonts/SourceCodePro-RegularItalic.ttf
          style: italic
        - asset: fonts/SourceCodePro-Bold.ttf
          weight: 700
        - asset: fonts/SourceCodePro-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Ubuntu Mono
      fonts:
        - asset: fonts/UbuntuMono-Regular.ttf
        - asset: fonts/UbuntuMono-RegularItalic.ttf
          style: italic
        - asset: fonts/UbuntuMono-Bold.ttf
          weight: 700
        - asset: fonts/UbuntuMono-BoldItalic.ttf
          style: italic
          weight: 700
    - family: Cascadia Code
      fonts:
        - asset: fonts/Cascadia.ttf
    - family: JetBrains Mono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
        - asset: fonts/JetBrainsMono-Italic.ttf
          style: italic
        - asset: fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: fonts/JetBrainsMono-Bold-Italic.ttf
          style: italic
          weight: 700
flutter_intl:
  enabled: true
